### ISSUE TITLE
Peer and Self Evaluation

### ISSUE THREAD

**Issue by fakaradin12** [SebCisneros/temp-repository-name#24]
Every team member complete Peer and Self Evaluation

https://docs.google.com/forms/d/e/1FAIpQLSe72s9bfbvqSariJ8VHnVB2fqXUzH6D9ifYWf9VmtyVeypY_Q/viewform?usp=sf_link

**Comment by SebCisneros** [comment]
I have completed mine

**Comment by fakaradin12** [comment]
I have completed mine.

**Comment by seongjae20** [comment]
I have completed mine.

**Comment by Sponge22** [comment]
I have completed mine.
